/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import model.Model;
import model.SoldProductsTableModel;

/**
 *
 * @author soto.aitzol
 */
public class View extends javax.swing.JFrame {

    /**
     * Creates new form View
     */
    public View() {
        initComponents();
    }
    
    public static View viewaSortuBistaratu() {
        View v = new View();
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                v.setVisible(true);
            }
        });
        return v;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDialogTextualReports = new javax.swing.JDialog();
        jLabel2 = new javax.swing.JLabel();
        jRadioButtonSoldProducts = new javax.swing.JRadioButton();
        jRadioButtonGarageOcuppation = new javax.swing.JRadioButton();
        jRadioButtonRentedHours = new javax.swing.JRadioButton();
        jRadioButtonIncomeByClient = new javax.swing.JRadioButton();
        jButton1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTableReports = new javax.swing.JTable();
        jDialogGraphicReports = new javax.swing.JDialog();
        jLabel = new javax.swing.JLabel();
        jRadioButtonReport1 = new javax.swing.JRadioButton();
        jRadioButtonReport2 = new javax.swing.JRadioButton();
        jRadioButtonReport3 = new javax.swing.JRadioButton();
        jRadioButtonReport4 = new javax.swing.JRadioButton();
        jDialogTextualReports1 = new javax.swing.JDialog();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextAreaTextualReports1 = new javax.swing.JTextArea();
        jRadioButtonSoldProducts1 = new javax.swing.JRadioButton();
        jRadioButtonGarageOcuppation1 = new javax.swing.JRadioButton();
        jRadioButtonRentedHours1 = new javax.swing.JRadioButton();
        jRadioButtonIncomeByClient1 = new javax.swing.JRadioButton();
        jButton2 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jButtonGraphicReports = new javax.swing.JButton();
        jButtonTextualReports = new javax.swing.JButton();

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("AHA GARAGE");

        jRadioButtonSoldProducts.setText("Most sold products");

        jRadioButtonGarageOcuppation.setText("Garage occupation");

        jRadioButtonRentedHours.setText("Rented hours by client");

        jRadioButtonIncomeByClient.setText("Income by client");

        jButton1.setBackground(new java.awt.Color(225, 225, 225));
        jButton1.setText("SAVE");

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("REPORTS");

        jTableReports.setModel(new SoldProductsTableModel(Model.mostSoldProductsArray()));
        jScrollPane3.setViewportView(jTableReports);

        javax.swing.GroupLayout jDialogTextualReportsLayout = new javax.swing.GroupLayout(jDialogTextualReports.getContentPane());
        jDialogTextualReports.getContentPane().setLayout(jDialogTextualReportsLayout);
        jDialogTextualReportsLayout.setHorizontalGroup(
            jDialogTextualReportsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialogTextualReportsLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 482, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                .addGroup(jDialogTextualReportsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jDialogTextualReportsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jRadioButtonIncomeByClient)
                        .addComponent(jRadioButtonRentedHours)
                        .addComponent(jRadioButtonGarageOcuppation)
                        .addComponent(jRadioButtonSoldProducts)
                        .addComponent(jButton1, javax.swing.GroupLayout.Alignment.TRAILING))
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22))
            .addGroup(jDialogTextualReportsLayout.createSequentialGroup()
                .addGap(195, 195, 195)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jDialogTextualReportsLayout.setVerticalGroup(
            jDialogTextualReportsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialogTextualReportsLayout.createSequentialGroup()
                .addGroup(jDialogTextualReportsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jDialogTextualReportsLayout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addComponent(jLabel3)
                        .addGap(27, 27, 27)
                        .addComponent(jRadioButtonSoldProducts)
                        .addGap(35, 35, 35)
                        .addComponent(jRadioButtonGarageOcuppation)
                        .addGap(31, 31, 31)
                        .addComponent(jRadioButtonRentedHours)
                        .addGap(36, 36, 36)
                        .addComponent(jRadioButtonIncomeByClient)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDialogTextualReportsLayout.createSequentialGroup()
                        .addContainerGap(7, Short.MAX_VALUE)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 462, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28))
        );

        jLabel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel.setText("AHA GARAGE");

        jRadioButtonReport1.setText("Report 1");

        jRadioButtonReport2.setText("Report 2");

        jRadioButtonReport3.setText("Report 3");

        jRadioButtonReport4.setText("Report 4");

        javax.swing.GroupLayout jDialogGraphicReportsLayout = new javax.swing.GroupLayout(jDialogGraphicReports.getContentPane());
        jDialogGraphicReports.getContentPane().setLayout(jDialogGraphicReportsLayout);
        jDialogGraphicReportsLayout.setHorizontalGroup(
            jDialogGraphicReportsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialogGraphicReportsLayout.createSequentialGroup()
                .addGap(103, 103, 103)
                .addComponent(jLabel)
                .addContainerGap(263, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDialogGraphicReportsLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jDialogGraphicReportsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jRadioButtonReport4)
                    .addComponent(jRadioButtonReport3)
                    .addComponent(jRadioButtonReport2)
                    .addComponent(jRadioButtonReport1))
                .addGap(47, 47, 47))
        );
        jDialogGraphicReportsLayout.setVerticalGroup(
            jDialogGraphicReportsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialogGraphicReportsLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel)
                .addGap(47, 47, 47)
                .addComponent(jRadioButtonReport1)
                .addGap(43, 43, 43)
                .addComponent(jRadioButtonReport2)
                .addGap(42, 42, 42)
                .addComponent(jRadioButtonReport3)
                .addGap(42, 42, 42)
                .addComponent(jRadioButtonReport4)
                .addContainerGap(49, Short.MAX_VALUE))
        );

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("AHA GARAGE");

        jTextAreaTextualReports1.setColumns(20);
        jTextAreaTextualReports1.setRows(5);
        jScrollPane2.setViewportView(jTextAreaTextualReports1);

        jRadioButtonSoldProducts1.setText("Most sold products");

        jRadioButtonGarageOcuppation1.setText("Garage occupation");

        jRadioButtonRentedHours1.setText("Rented hours by client");

        jRadioButtonIncomeByClient1.setText("Income by client");

        jButton2.setBackground(new java.awt.Color(225, 225, 225));
        jButton2.setText("SAVE");

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("REPORTS");

        javax.swing.GroupLayout jDialogTextualReports1Layout = new javax.swing.GroupLayout(jDialogTextualReports1.getContentPane());
        jDialogTextualReports1.getContentPane().setLayout(jDialogTextualReports1Layout);
        jDialogTextualReports1Layout.setHorizontalGroup(
            jDialogTextualReports1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialogTextualReports1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 305, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addGroup(jDialogTextualReports1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jDialogTextualReports1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jRadioButtonIncomeByClient1)
                        .addComponent(jRadioButtonRentedHours1)
                        .addComponent(jRadioButtonGarageOcuppation1)
                        .addComponent(jRadioButtonSoldProducts1)
                        .addComponent(jButton2, javax.swing.GroupLayout.Alignment.TRAILING))
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22))
            .addGroup(jDialogTextualReports1Layout.createSequentialGroup()
                .addGap(82, 82, 82)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jDialogTextualReports1Layout.setVerticalGroup(
            jDialogTextualReports1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialogTextualReports1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(jLabel5)
                .addGroup(jDialogTextualReports1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jDialogTextualReports1Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(64, Short.MAX_VALUE))
                    .addGroup(jDialogTextualReports1Layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(jRadioButtonSoldProducts1)
                        .addGap(35, 35, 35)
                        .addComponent(jRadioButtonGarageOcuppation1)
                        .addGap(31, 31, 31)
                        .addComponent(jRadioButtonRentedHours1)
                        .addGap(35, 35, 35)
                        .addComponent(jRadioButtonIncomeByClient1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28))))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("AHA GARAGE");

        jButtonGraphicReports.setBackground(new java.awt.Color(225, 225, 225));
        jButtonGraphicReports.setText("GRAPHIC REPORTS");

        jButtonTextualReports.setBackground(new java.awt.Color(225, 225, 225));
        jButtonTextualReports.setText("TEXTUAL REPORTS");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addComponent(jButtonGraphicReports, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonTextualReports, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(49, 49, 49))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(171, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(168, 168, 168))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(79, 79, 79)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonGraphicReports, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonTextualReports, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(102, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new View().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    public javax.swing.JButton jButtonGraphicReports;
    public javax.swing.JButton jButtonTextualReports;
    public javax.swing.JDialog jDialogGraphicReports;
    public javax.swing.JDialog jDialogTextualReports;
    public javax.swing.JDialog jDialogTextualReports1;
    javax.swing.JLabel jLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    public javax.swing.JRadioButton jRadioButtonGarageOcuppation;
    public javax.swing.JRadioButton jRadioButtonGarageOcuppation1;
    public javax.swing.JRadioButton jRadioButtonIncomeByClient;
    public javax.swing.JRadioButton jRadioButtonIncomeByClient1;
    public javax.swing.JRadioButton jRadioButtonRentedHours;
    public javax.swing.JRadioButton jRadioButtonRentedHours1;
    public javax.swing.JRadioButton jRadioButtonReport1;
    public javax.swing.JRadioButton jRadioButtonReport2;
    public javax.swing.JRadioButton jRadioButtonReport3;
    public javax.swing.JRadioButton jRadioButtonReport4;
    public javax.swing.JRadioButton jRadioButtonSoldProducts;
    public javax.swing.JRadioButton jRadioButtonSoldProducts1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    public javax.swing.JTable jTableReports;
    public javax.swing.JTextArea jTextAreaTextualReports1;
    // End of variables declaration//GEN-END:variables
}
