/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import model.Model;
import model.SoldProductsTableModel;

/**
 *
 * @author soto.aitzol
 */
public class View extends javax.swing.JFrame {

    /**
     * Creates new form View
     */
    public View() {
        initComponents();
    }
    
    public static View viewaSortuBistaratu() {
        View v = new View();
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                v.setVisible(true);
            }
        });
        return v;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDialogTextualReports = new javax.swing.JDialog();
        jLabel2 = new javax.swing.JLabel();
        jRadioButtonSoldProducts = new javax.swing.JRadioButton();
        jRadioButtonGarageOcuppation = new javax.swing.JRadioButton();
        jRadioButtonProductsByMonth = new javax.swing.JRadioButton();
        jRadioButtonTotalRentedHours = new javax.swing.JRadioButton();
        jButtonSave = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTableReports = new javax.swing.JTable();
        jComboBoxHilabetea = new javax.swing.JComboBox<>();
        jRadioButtonEmployeeByPosition = new javax.swing.JRadioButton();
        jComboBoxEmployeePos = new javax.swing.JComboBox<>();
        jRadioButtonTotalIncomeByMonth = new javax.swing.JRadioButton();
        jComboBoxYear = new javax.swing.JComboBox<>();
        jDialogGraphicReports = new javax.swing.JDialog();
        jLabel = new javax.swing.JLabel();
        jRadioButtonReport1 = new javax.swing.JRadioButton();
        jRadioButtonReport2 = new javax.swing.JRadioButton();
        jRadioButtonReport3 = new javax.swing.JRadioButton();
        jLabel4 = new javax.swing.JLabel();
        jComboBoxYearGraphics = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jButtonGraphicReports = new javax.swing.JButton();
        jButtonTextualReports = new javax.swing.JButton();
        jLabelLogo = new javax.swing.JLabel();

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("AHA GARAGE");

        jRadioButtonSoldProducts.setText("Most sold products");

        jRadioButtonGarageOcuppation.setText("Garage occupation");

        jRadioButtonProductsByMonth.setText("Most sold products by month");

        jRadioButtonTotalRentedHours.setText("Total rented hours by client");

        jButtonSave.setBackground(new java.awt.Color(225, 225, 225));
        jButtonSave.setText("SAVE");

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("REPORTS");

        jTableReports.setModel(new SoldProductsTableModel(Model.mostSoldProductsArray()));
        jScrollPane3.setViewportView(jTableReports);

        jComboBoxHilabetea.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "January", "February", "March", "April", "May ", "June ", "July ", "August", "September", "October", "November", "December" }));

        jRadioButtonEmployeeByPosition.setText("Employees by position");

        jComboBoxEmployeePos.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Mechanic", "Cleaner", "Security", "Boss" }));
        jComboBoxEmployeePos.setActionCommand("positionComboBox");

        jRadioButtonTotalIncomeByMonth.setText("Total income by month");

        jComboBoxYear.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "2022", "2021", " " }));
        jComboBoxYear.setActionCommand("yearComboBox");

        javax.swing.GroupLayout jDialogTextualReportsLayout = new javax.swing.GroupLayout(jDialogTextualReports.getContentPane());
        jDialogTextualReports.getContentPane().setLayout(jDialogTextualReportsLayout);
        jDialogTextualReportsLayout.setHorizontalGroup(
            jDialogTextualReportsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialogTextualReportsLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jDialogTextualReportsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 482, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jDialogTextualReportsLayout.createSequentialGroup()
                        .addComponent(jComboBoxHilabetea, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jComboBoxEmployeePos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jComboBoxYear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jDialogTextualReportsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jDialogTextualReportsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jRadioButtonTotalRentedHours)
                        .addComponent(jRadioButtonProductsByMonth)
                        .addComponent(jRadioButtonGarageOcuppation)
                        .addComponent(jRadioButtonSoldProducts)
                        .addComponent(jButtonSave, javax.swing.GroupLayout.Alignment.TRAILING))
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jRadioButtonEmployeeByPosition)
                    .addComponent(jRadioButtonTotalIncomeByMonth, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22))
            .addGroup(jDialogTextualReportsLayout.createSequentialGroup()
                .addGap(284, 284, 284)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jDialogTextualReportsLayout.setVerticalGroup(
            jDialogTextualReportsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialogTextualReportsLayout.createSequentialGroup()
                .addGroup(jDialogTextualReportsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jDialogTextualReportsLayout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addComponent(jLabel3)
                        .addGap(27, 27, 27))
                    .addGroup(jDialogTextualReportsLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jDialogTextualReportsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jComboBoxHilabetea, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jComboBoxEmployeePos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jComboBoxYear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                .addGroup(jDialogTextualReportsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jDialogTextualReportsLayout.createSequentialGroup()
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 462, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(37, 37, 37))
                    .addGroup(jDialogTextualReportsLayout.createSequentialGroup()
                        .addComponent(jRadioButtonSoldProducts)
                        .addGap(32, 32, 32)
                        .addComponent(jRadioButtonGarageOcuppation)
                        .addGap(34, 34, 34)
                        .addComponent(jRadioButtonProductsByMonth)
                        .addGap(36, 36, 36)
                        .addComponent(jRadioButtonTotalRentedHours)
                        .addGap(32, 32, 32)
                        .addComponent(jRadioButtonEmployeeByPosition)
                        .addGap(34, 34, 34)
                        .addComponent(jRadioButtonTotalIncomeByMonth)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonSave, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28))))
        );

        jLabel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel.setText("AHA GARAGE");

        jRadioButtonReport1.setText("Total income");

        jRadioButtonReport2.setText("Garage occupation by month");

        jRadioButtonReport3.setText("Most sold products");
        jRadioButtonReport3.setActionCommand("Products graphic");
        jRadioButtonReport3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonReport3ActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("REPORTS");

        jComboBoxYearGraphics.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "2022", "2021" }));
        jComboBoxYearGraphics.setActionCommand("comboBoxYearGraphics");

        jLabel5.setText("YEAR");

        javax.swing.GroupLayout jDialogGraphicReportsLayout = new javax.swing.GroupLayout(jDialogGraphicReports.getContentPane());
        jDialogGraphicReports.getContentPane().setLayout(jDialogGraphicReportsLayout);
        jDialogGraphicReportsLayout.setHorizontalGroup(
            jDialogGraphicReportsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialogGraphicReportsLayout.createSequentialGroup()
                .addContainerGap(553, Short.MAX_VALUE)
                .addGroup(jDialogGraphicReportsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDialogGraphicReportsLayout.createSequentialGroup()
                        .addGroup(jDialogGraphicReportsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jRadioButtonReport3)
                            .addComponent(jRadioButtonReport2)
                            .addComponent(jRadioButtonReport1)
                            .addGroup(jDialogGraphicReportsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jComboBoxYearGraphics, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGap(21, 21, 21))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDialogGraphicReportsLayout.createSequentialGroup()
                        .addComponent(jLabel)
                        .addGap(537, 537, 537))))
        );
        jDialogGraphicReportsLayout.setVerticalGroup(
            jDialogGraphicReportsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialogGraphicReportsLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel)
                .addGap(60, 60, 60)
                .addComponent(jLabel4)
                .addGap(27, 27, 27)
                .addComponent(jRadioButtonReport1)
                .addGap(43, 43, 43)
                .addComponent(jRadioButtonReport2)
                .addGap(42, 42, 42)
                .addComponent(jRadioButtonReport3)
                .addGap(38, 38, 38)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jComboBoxYearGraphics, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(229, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("AHA GARAGE");

        jButtonGraphicReports.setBackground(new java.awt.Color(225, 225, 225));
        jButtonGraphicReports.setText("GRAPHIC REPORTS");

        jButtonTextualReports.setBackground(new java.awt.Color(225, 225, 225));
        jButtonTextualReports.setText("TEXTUAL REPORTS");
        jButtonTextualReports.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonTextualReportsActionPerformed(evt);
            }
        });

        jLabelLogo.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabelLogo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(87, 87, 87)
                .addComponent(jButtonGraphicReports, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonTextualReports, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(55, 55, 55))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(250, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(264, 264, 264))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabelLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(232, 232, 232))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabelLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonTextualReports, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonGraphicReports, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(77, 77, 77))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonTextualReportsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonTextualReportsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonTextualReportsActionPerformed

    private void jRadioButtonReport3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonReport3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButtonReport3ActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new View().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton jButtonGraphicReports;
    public javax.swing.JButton jButtonSave;
    public javax.swing.JButton jButtonTextualReports;
    public javax.swing.JComboBox<String> jComboBoxEmployeePos;
    public javax.swing.JComboBox<String> jComboBoxHilabetea;
    public javax.swing.JComboBox<String> jComboBoxYear;
    public javax.swing.JComboBox<String> jComboBoxYearGraphics;
    public javax.swing.JDialog jDialogGraphicReports;
    public javax.swing.JDialog jDialogTextualReports;
    javax.swing.JLabel jLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    public javax.swing.JLabel jLabelLogo;
    public javax.swing.JRadioButton jRadioButtonEmployeeByPosition;
    public javax.swing.JRadioButton jRadioButtonGarageOcuppation;
    public javax.swing.JRadioButton jRadioButtonProductsByMonth;
    public javax.swing.JRadioButton jRadioButtonReport1;
    public javax.swing.JRadioButton jRadioButtonReport2;
    public javax.swing.JRadioButton jRadioButtonReport3;
    public javax.swing.JRadioButton jRadioButtonSoldProducts;
    public javax.swing.JRadioButton jRadioButtonTotalIncomeByMonth;
    public javax.swing.JRadioButton jRadioButtonTotalRentedHours;
    private javax.swing.JScrollPane jScrollPane3;
    public javax.swing.JTable jTableReports;
    // End of variables declaration//GEN-END:variables
}
